name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Runs when a new tag like v1.0.0 is pushed
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest  # Uses Ubuntu as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          python -m pip install pyinstaller fpm

      - name: Build Python Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile src/cuecreator/Cue_Creator.py
        working-directory: .  # Ensure this is the correct working directory where `main.py` is located

      - name: Create .deb package using fpm
        run: |
          fpm -s dir -t deb -n cuecreator -v 1.0.0 --prefix /usr/local/bin -C /home/runner/work/CueCreator/CueCreator/dist .

      - name: Upload .deb package
        uses: softprops/action-gh-release@v1
        with:
          files: dist/cuecreator-1.0.0.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*  # Upload all files in dist/ directory (source distribution, wheel, executables)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is needed to create the release on GitHub
