name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Runs when a new tag like v1.0.0 is pushed
  workflow_dispatch:  # This allows manual trigger from Actions tab

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest  # Uses Ubuntu as the runner
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: List files in the root directory
        run: |
          ls -la
      
      - name: Build Python Package
        run: |
          python -m build  # Build the package using pyproject.toml (creates distribution files in dist/)
          working-directory: ./ 

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*  # Upload all files in the dist/ directory (e.g., wheel, tar.gz)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is needed to create the release on GitHub
