name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Runs when a new tag like v1.0.0 is pushed
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest  # Uses Ubuntu as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
        
      - name: Install Dependencies
        run: |
          poetry install  # Install dependencies defined in pyproject.toml

      - name: Build Python Package with Poetry
        run: |
          poetry build  # Build the package using Poetry (creates distribution files in dist/)
        working-directory: .

      - name: List files in dist/ directory
        run: |
          echo "Listing all files in dist/ directory:"
          ls -la dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*  # Upload all files in the dist/ directory (e.g., wheel, tar.gz)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is needed to create the release on GitHub
